### ISSUE TITLE
Unable to install extension

### ISSUE THREAD

**Issue by rbicera0407** [szkiba/xk6-mock#2]
I've installed go, and tried running the command to build the binary, but i receive the following:

Command:  xk6 build --with github.com/szkiba/xk6-mock@latest

# github.com/szkiba/xk6-mock
../../../go/pkg/mod/github.com/szkiba/xk6-mock@v0.1.2/http.go:36:15: undefined: "go.k6.io/k6/js/modules/k6/http".ToURL
../../../go/pkg/mod/github.com/szkiba/xk6-mock@v0.1.2/http.go:41:10: cannot assign error to err in multiple assignment
../../../go/pkg/mod/github.com/szkiba/xk6-mock@v0.1.2/http.go:51:12: cannot assign httpext.URL to orig in multiple assignment
../../../go/pkg/mod/github.com/szkiba/xk6-mock@v0.1.2/http.go:51:12: cannot assign error to err in multiple assignment
2021/11/12 09:57:03 [INFO] Cleaning up temporary folder: /Users/92041/Repos/go/buildenv_2021-11-12-0957.1256646309
2021/11/12 09:57:03 [FATAL] exit status 2

**Comment by szkiba** [comment]
Thank you for feedback. It's fixed now, version v0.2.0 
(the minimum k6 version is v0.43.0)

**Comment by szkiba** [comment]
fixed
