### ISSUE TITLE
Built binary file treated as virus

### ISSUE THREAD

**Issue by andriuspit** [szkiba/xk6-mock#7]
Tried downloading and building extension binary, but I wasn't able to run it, because Windows Defender treated built binary as virus
![image](https://github.com/szkiba/xk6-mock/assets/15904045/a0c4b12c-9c38-40d2-8feb-b1a80a0d90af)

Tried to use prebuilt binary and windows defender did not complained

**Comment by szkiba** [comment]
It's probably a local problem. There could be a conflict between the go compiler and defender settings, but it could also be that the machine really has a virus.
